### PR TITLE
Unit Test Refactoring

### PR DESCRIPTION
**Pull request by arielmagbanua**
* Cleaned up unused imports and variables.
* Replaced deprecated test functions.

image

### CODE REVIEW

**Comment by jfschmakeit** [comment]
Thanks for the pull request(s)! I'm hoping to get back to you in the next couple of days with a review. 

(Unfortunately these changes may not be quite as straight forward to merge in, as some of these files are actually autogenerated. This makes any manual changes difficult to reconcile in the future. Please stay tuned for the review.)

**Comment by arielmagbanua** [comment]
@jfschmakeit Oh I see, so the tests were autogenerated as well? My bad, I didn't noticed. If it is not needed anymore feel free to close it, thanks.

**Comment by jfschmakeit** [comment]
I believe we should be able to merge the files that have been modified here. (Regarding tests - only `PhotosLibraryClientTest.php` is generated.)

However, please be mindful of adding new method and class comments. They should provide additional details and explanations. For simplicity, it can sometimes be best to omit them. For example, please review the comments in the files `PhotosLibraryClientWrapperTest.php`, ` PhotosLibraryClientTest.php`.

Thanks for preparing this pull request!

**Comment by arielmagbanua** [comment]
@jfschmakeit Thanks! I will add more details or documentation or update the comments.

**Comment by arielmagbanua** [comment]
@jfschmakeit

* I removed the unecessary comments.
* Restored the auto generated `PhotosLibraryClientTest.php`.

**Pull request merged**
